name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Clear cache
        run: npm cache clean --force

      - name: Checkout
        uses: actions/checkout@v2
        with:
          config-file: cypress.config.js
          record: false
          headless: true

      - name: Cypress run
        uses: cypress-io/github-action@v2
